import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))


tamanhos_regioes_fito_ecologias = {
    "Floresta Estacional": {
        "1 time": {"descricao":"Florestas tropicais caracterizadas por uma marcante estação seca, durante a qual perdem parcial ou totalmente suas folhas, sendo classificadas como decíduas ou semicaducifólias. Essa perda foliar é uma adaptação natural ao déficit hídrico que ocorre nesse período. Essas formações vegetais ocorrem principalmente em áreas de transição ecológica, como entre o Cerrado e a Amazônia, além de porções interiores da Mata Atlântica. Apresentam estratificação bem definida, elevada biodiversidade e geralmente se desenvolvem sobre solos de boa fertilidade. Dividem-se em dois tipos principais: Floresta Estacional Decidual, com perda foliar intensa, e Floresta Estacional Semidecidual, com perda parcial das folhas. São ecossistemas de grande importância ecológica e econômica, fundamentais para a conservação de recursos hídricos e para a exploração madeireira, mas enfrentam forte pressão devido à expansão agrícola.",
                  "borda":"10"},
        "2 time": {"descricao":"Florestas tropicais caracterizadas por uma marcante estação seca, durante a qual perdem parcial ou totalmente suas folhas, sendo classificadas como decíduas ou semicaducifólias. Essa perda foliar é uma adaptação natural ao déficit hídrico que ocorre nesse período. Essas formações vegetais ocorrem principalmente em áreas de transição ecológica, como entre o Cerrado e a Amazônia, além de porções interiores da Mata Atlântica. Apresentam estratificação bem definida, elevada biodiversidade e geralmente se desenvolvem sobre solos de boa fertilidade.",
                    "borda":"8"},
        "3 time": {"descricao":"Florestas tropicais caracterizadas por uma marcante estação seca, durante a qual perdem parcial ou totalmente suas folhas, sendo classificadas como decíduas ou semicaducifólias. Essa perda foliar é uma adaptação natural ao déficit hídrico que ocorre nesse período. Essas formações vegetais ocorrem principalmente em áreas de transição ecológica, como entre o Cerrado e a Amazônia, além de porções interiores da Mata Atlântica.",
                    "borda":"6,75"},
        "4 time": {"descricao":"Florestas tropicais caracterizadas por uma marcante estação seca, durante a qual perdem parcial ou totalmente suas folhas, sendo classificadas como decíduas ou semicaducifólias. Essa perda foliar é uma adaptação natural ao déficit hídrico que ocorre nesse período. Essas formações vegetais ocorrem principalmente em áreas de transição ecológica.",
                    "borda":"7,25"}
    },
    "Floresta Ombrófila Aberta": {
        "1 time": {"descricao":"Floresta úmida que se caracteriza por um dossel mais baixo e menos fechado em comparação à Floresta Ombrófila Densa, o que permite uma maior penetração de luz até os estratos inferiores da vegetação. Esse tipo florestal é comumente encontrado em áreas de transição entre a Amazônia e o Cerrado, bem como em regiões com índices pluviométricos mais moderados ou solos de menor fertilidade, como é o caso das campinaranas. A vegetação apresenta adaptações específicas a solos arenosos, ácidos e geralmente pobres em nutrientes (oligotróficos). Espécies de palmeiras como o babaçu e o açaí são especialmente abundantes, compondo parte importante da estrutura ecológica e econômica local. Embora a biodiversidade ainda seja significativa, é relativamente menor do que na Floresta Densa. Essa formação florestal enfrenta ameaças constantes devido à expansão da agropecuária e da mineração, desempenhando, no entanto, um papel essencial na subsistência e cultura de populações tradicionais e comunidades indígenas.",
                  "borda":"9,2"},
        "2 time": {"descricao":"Floresta úmida que se caracteriza por um dossel mais baixo e menos fechado em comparação à Floresta Ombrófila Densa, o que permite uma maior penetração de luz até os estratos inferiores da vegetação. Esse tipo florestal é comumente encontrado em áreas de transição entre a Amazônia e o Cerrado, bem como em regiões com índices pluviométricos mais moderados ou solos de menor fertilidade, como é o caso das campinaranas. A vegetação apresenta adaptações específicas a solos arenosos, ácidos e geralmente pobres em nutrientes (oligotróficos). Espécies de palmeiras como o babaçu e o açaí são especialmente abundantes, compondo parte importante da estrutura ecológica e econômica local.",
                    "borda":"7,9"},
        "3 time": {"descricao":"Floresta úmida que se caracteriza por um dossel mais baixo e menos fechado em comparação à Floresta Ombrófila Densa, o que permite uma maior penetração de luz até os estratos inferiores da vegetação. Esse tipo florestal é comumente encontrado em áreas de transição entre a Amazônia e o Cerrado, bem como em regiões com índices pluviométricos mais moderados ou solos de menor fertilidade, como é o caso das campinaranas. A vegetação apresenta adaptações específicas a solos arenosos.",
                    "borda":"6,65"},
        "4 time": {"descricao":"Floresta úmida que se caracteriza por um dossel mais baixo e menos fechado em comparação à Floresta Ombrófila Densa, o que permite uma maior penetração de luz até os estratos inferiores da vegetação.",
                    "borda":"7,7"}
    },
    "Floresta Ombrófila Densa": {
        "1 time": {"descricao":"Conhecida como a clássica “floresta tropical úmida”, essa formação é perene, alta — com dossel variando entre 30 e 40 metros de altura —, extremamente densa e marcada por exuberância vegetal. Está presente principalmente na região Amazônica e na faixa costeira da Mata Atlântica, onde predominam condições climáticas úmidas, com chuvas intensas e bem distribuídas ao longo do ano (acima de 2000 mm/ano), além de elevada umidade relativa do ar. Os solos são, em geral, profundos e bem desenvolvidos, porém frequentemente ácidos e pobres em nutrientes, o que torna a ciclagem biogeoquímica essencial para a manutenção da floresta. Apresenta uma estrutura vertical complexa, com vários estratos bem definidos, abundância de epífitas, lianas e árvores emergentes. É considerada o ecossistema terrestre com maior biodiversidade do planeta, abrigando uma imensa variedade de espécies animais e vegetais. Desempenha funções ecológicas vitais, como atuar como sumidouro de carbono, regular o ciclo hidrológico e contribuir para o equilíbrio climático em escala regional e global. No entanto, encontra-se severamente ameaçada pelas atividades humanas, sobretudo o desmatamento voltado à extração de madeira, à expansão agropecuária e à urbanização desordenada.",
                  "borda":"8,1"},
        "2 time": {"descricao":"Conhecida como a clássica “floresta tropical úmida”, essa formação é perene, alta — com dossel variando entre 30 e 40 metros de altura —, extremamente densa e marcada por exuberância vegetal. Está presente principalmente na região Amazônica e na faixa costeira da Mata Atlântica, onde predominam condições climáticas úmidas, com chuvas intensas e bem distribuídas ao longo do ano (acima de 2000 mm/ano), além de elevada umidade relativa do ar. Os solos são, em geral, profundos e bem desenvolvidos, porém frequentemente ácidos e pobres em nutrientes.",
                    "borda":"7,7"},
        "3 time": {"descricao":"Conhecida como a clássica “floresta tropical úmida”, essa formação é perene, alta — com dossel variando entre 30 e 40 metros de altura —, extremamente densa e marcada por exuberância vegetal. Está presente principalmente na região Amazônica e na faixa costeira da Mata Atlântica, onde predominam condições climáticas úmidas, com chuvas intensas e bem distribuídas ao longo do ano (acima de 2000 mm/ano), além de elevada umidade relativa do ar.",
                    "borda":"5,1"},
        "4 time": {"descricao":"Conhecida como a clássica “floresta tropical úmida”, essa formação é perene, alta — com dossel variando entre 30 e 40 metros de altura —, extremamente densa e marcada por exuberância vegetal. Está presente principalmente na região Amazônica e na faixa costeira da Mata Atlântica.",
                    "borda":"6,63"}
    },
    "Savana Gramíneo Lenhosa": {
        "1 time": {"descricao":"Fitofisionomia aberta do bioma Cerrado, caracterizada pela predominância de uma extensa e densa camada herbácea, composta majoritariamente por gramíneas nativas. Essa vegetação rasteira é intercalada por arbustos e subarbustos lenhosos esparsos, geralmente com altura inferior a 2 metros. Árvores são muito raras ou completamente ausentes, o que reforça o caráter campestre dessa formação. Ocorre principalmente em áreas com solos rasos, ácidos, pedregosos ou de baixa fertilidade, o que limita o desenvolvimento de vegetação arbórea mais robusta. Essa paisagem é altamente adaptada à ocorrência periódica de fogo natural — as gramíneas, por exemplo, possuem elevada capacidade de rebrote após incêndios, o que contribui para a resiliência ecológica do ambiente. A biodiversidade, embora menos visível, é notável especialmente no estrato rasteiro, onde há grande variedade de insetos, pequenos roedores, répteis e outras formas de vida adaptadas ao microclima do solo. Esta fitofisionomia desempenha papel fundamental na formação de pastagens nativas e no suporte à pecuária extensiva tradicional, mas encontra-se ameaçada pela invasão de gramíneas exóticas africanas, que alteram a dinâmica ecológica, e pela crescente conversão do solo para a agricultura mecanizada.",
                    "borda":"8"},
        "2 time": {"descricao":"Fitofisionomia aberta do bioma Cerrado, caracterizada pela predominância de uma extensa e densa camada herbácea, composta majoritariamente por gramíneas nativas. Essa vegetação rasteira é intercalada por arbustos e subarbustos lenhosos esparsos, geralmente com altura inferior a 2 metros. Árvores são muito raras ou completamente ausentes, o que reforça o caráter campestre dessa formação. Ocorre principalmente em áreas com solos rasos, ácidos, pedregosos ou de baixa fertilidade, o que limita o desenvolvimento de vegetação arbórea mais robusta.",
                    "borda":"7,85"},
        "3 time": {"descricao":"Fitofisionomia aberta do bioma Cerrado, caracterizada pela predominância de uma extensa e densa camada herbácea, composta majoritariamente por gramíneas nativas. Essa vegetação rasteira é intercalada por arbustos e subarbustos lenhosos esparsos, geralmente com altura inferior a 2 metros. Árvores são muito raras ou completamente ausentes, o que reforça o caráter campestre dessa formação. Ocorre principalmente em áreas com solos rasos, ácidos, pedregosos ou de baixa fertilidade.",
                    "borda":"5,9"},
        "4 time": {"descricao":"Fitofisionomia aberta do bioma Cerrado, caracterizada pela predominância de uma extensa e densa camada herbácea, composta majoritariamente por gramíneas nativas. Essa vegetação rasteira é intercalada por arbustos e subarbustos.",
                    "borda":"7"}
    },
    "Savana Arborizada/Arbórea": {
        "1 time": {"descricao":"Trata-se da savana arborizada típica e mais representativa do bioma Cerrado, conhecida como sua fitofisionomia clássica. É caracterizada por um estrato herbáceo-arbustivo contínuo, dominado por gramíneas nativas e pequenos arbustos, que cobre o solo de forma densa. Acima desse estrato, desenvolve-se um componente arbóreo descontínuo, composto por árvores espaçadas, retorcidas, com alturas variando entre 3 e 8 metros e copas irregulares. A cobertura arbórea é intermediária, situando-se entre 10% e 40%, o que permite significativa entrada de luz até o sub-bosque. As árvores apresentam adaptações marcantes às condições ambientais restritivas: casca espessa e corticosa, resistência ao fogo natural e raízes profundas que lhes permitem acessar a umidade em solos ácidos, rasos e de baixa fertilidade. Essa estrutura complexa sustenta uma biodiversidade extremamente alta, com destaque para a flora adaptada e uma diversidade notável de insetos, fundamentais para a polinização e o equilíbrio ecológico. É considerada o núcleo ecológico do Cerrado e ocupa a maior parte da área do bioma. No entanto, por sua topografia plana e facilidade de mecanização, essa fitofisionomia é a mais afetada pela expansão agrícola — especialmente a soja — e pela intensificação da pecuária, sendo alvo constante de desmatamento e degradação ambiental.",
                    "borda":"7,95"},
        "2 time": {"descricao":"Trata-se da savana arborizada típica e mais representativa do bioma Cerrado, conhecida como sua fitofisionomia clássica. É caracterizada por um estrato herbáceo-arbustivo contínuo, dominado por gramíneas nativas e pequenos arbustos, que cobre o solo de forma densa. Acima desse estrato, desenvolve-se um componente arbóreo descontínuo, composto por árvores espaçadas, retorcidas, com alturas variando entre 3 e 8 metros e copas irregulares. A cobertura arbórea é intermediária, situando-se entre 10% e 40%, o que permite significativa entrada de luz até o sub-bosque. As árvores apresentam adaptações marcantes às condições ambientais restritivas",
                    "borda":"7,4"},
        "3 time": {"descricao":"Trata-se da savana arborizada típica e mais representativa do bioma Cerrado, conhecida como sua fitofisionomia clássica. É caracterizada por um estrato herbáceo-arbustivo contínuo, dominado por gramíneas nativas e pequenos arbustos, que cobre o solo de forma densa. Acima desse estrato, desenvolve-se um componente arbóreo descontínuo, composto por árvores espaçadas, retorcidas, com alturas variando entre 3 e 8 metros e copas irregulares.",
                    "borda":"6,7"},
        "4 time": {"descricao":"Trata-se da savana arborizada típica e mais representativa do bioma Cerrado, conhecida como sua fitofisionomia clássica. É caracterizada por um estrato herbáceo-arbustivo contínuo, dominado por gramíneas nativas e pequenos arbustos, que cobre o solo de forma densa.",
                    "borda":"7"}
    },
    "Savana Florestada": {
        "1 time": {"descricao":"Essa fitofisionomia representa uma zona de transição ecológica entre o Cerrado stricto sensu e as formações florestais adjacentes, como matas de galeria ou florestas estacionais. Caracteriza-se por um dossel mais fechado do que nas savanas típicas, com cobertura arbórea variando entre 50% e 90%, formada por árvores com altura média entre 8 e 15 metros. Apesar desse aspecto mais florestal, o sub-bosque ainda mantém elementos típicos das savanas, com presença significativa de gramíneas e arbustos lenhosos, criando um ambiente híbrido. Os solos são semelhantes aos do Cerrado típico — ácidos, com baixa fertilidade e, em muitos casos, bem drenados —, embora essa fitofisionomia ocorra preferencialmente em áreas com solos um pouco mais profundos. Ao contrário das formações savânicas mais abertas, sua vegetação é menos adaptada ao fogo, sendo mais suscetível a danos por queimadas frequentes. A biodiversidade é mista e rica, abrigando espécies tanto do Cerrado quanto de formações florestais, o que confere alto valor ecológico às suas manchas de vegetação. Com distribuição em mosaico, geralmente formando manchas irregulares dentro da paisagem cerratense, essas áreas sofrem forte vulnerabilidade frente ao corte seletivo de madeira, à exploração desordenada de recursos e à conversão do uso do solo para atividades agropecuárias.",
                    "borda":"7,6"},
        "2 time": {"descricao":"Essa fitofisionomia representa uma zona de transição ecológica entre o Cerrado stricto sensu e as formações florestais adjacentes, como matas de galeria ou florestas estacionais. Caracteriza-se por um dossel mais fechado do que nas savanas típicas, com cobertura arbórea variando entre 50% e 90%, formada por árvores com altura média entre 8 e 15 metros. Apesar desse aspecto mais florestal, o sub-bosque ainda mantém elementos típicos das savanas, com presença significativa de gramíneas e arbustos lenhosos, criando um ambiente híbrido. Os solos são semelhantes aos do Cerrado típico.",
                    "borda":"7,65"},
        "3 time": {"descricao":"Essa fitofisionomia representa uma zona de transição ecológica entre o Cerrado stricto sensu e as formações florestais adjacentes, como matas de galeria ou florestas estacionais. Caracteriza-se por um dossel mais fechado do que nas savanas típicas, com cobertura arbórea variando entre 50% e 90%, formada por árvores com altura média entre 8 e 15 metros. Apesar desse aspecto mais florestal, o sub-bosque ainda mantém elementos típicos das savanas.",
                    "borda":"6"},
        "4 time": {"descricao":"Essa fitofisionomia representa uma zona de transição ecológica entre o Cerrado stricto sensu e as formações florestais adjacentes, como matas de galeria ou florestas estacionais. Caracteriza-se por um dossel mais fechado do que nas savanas típicas.",
                    "borda":"7"}
    },
    "Savana Parque": {
        "1 time": {"descricao":"Fitofisionomia úmida típica do bioma Cerrado, conhecida por sua forte associação a ambientes com solos hidromórficos — constantemente encharcados devido à proximidade do lençol freático ou à presença de nascentes. Essa formação vegetacional é marcada por agrupamentos densos da palmeira buriti (Mauritia flexuosa), que se destacam visualmente na paisagem por sua altura, podendo ultrapassar os 15 metros, e por emergirem sobre um estrato herbáceo contínuo, formado principalmente por gramíneas e ciperáceas adaptadas à saturação hídrica. Os buritizais ocorrem preferencialmente ao longo de vales úmidos e margens de cursos d'água, formando verdadeiros corredores ecológicos que desempenham papel essencial na conservação dos recursos hídricos — atuando como áreas de recarga e proteção de nascentes — e como refúgio para a fauna durante os períodos de seca. A biodiversidade é especializada e restrita a espécies adaptadas às condições úmidas, tanto da flora quanto da fauna, incluindo aves, anfíbios e insetos endêmicos desses ambientes. No entanto, trata-se de uma das fitofisionomias mais sensíveis à ação antrópica, sendo extremamente vulnerável ao assoreamento causado pelo desmatamento das margens, ao pisoteio por gado, à contaminação das águas e à drenagem artificial para fins agrícolas, o que compromete sua regeneração natural e suas funções ecológicas.",
                    "borda":"7,3"},
        "2 time": {"descricao":"Fitofisionomia úmida típica do bioma Cerrado, conhecida por sua forte associação a ambientes com solos hidromórficos — constantemente encharcados devido à proximidade do lençol freático ou à presença de nascentes. Essa formação vegetacional é marcada por agrupamentos densos da palmeira buriti (Mauritia flexuosa), que se destacam visualmente na paisagem por sua altura, podendo ultrapassar os 15 metros, e por emergirem sobre um estrato herbáceo contínuo, formado principalmente por gramíneas e ciperáceas adaptadas à saturação hídrica. Os buritizais ocorrem preferencialmente ao longo de vales úmidos e margens de cursos d'água.",
                    "borda":"7,1"},
        "3 time": {"descricao":"Fitofisionomia úmida típica do bioma Cerrado, conhecida por sua forte associação a ambientes com solos hidromórficos — constantemente encharcados devido à proximidade do lençol freático ou à presença de nascentes. Essa formação vegetacional é marcada por agrupamentos densos da palmeira buriti (Mauritia flexuosa), que se destacam visualmente na paisagem por sua altura, podendo ultrapassar os 15 metros, e por emergirem sobre um estrato herbáceo contínuo.",
                    "borda":"5,8"},
        "4 time": {"descricao":"Fitofisionomia úmida típica do bioma Cerrado, conhecida por sua forte associação a ambientes com solos hidromórficos constantemente encharcados devido à proximidade do lençol freático ou à presença de nascentes.",
                    "borda":"6,9"}
    },
    "Rio": {
        "1 time": {"descricao":"Embora os rios não sejam considerados uma fitofisionomia terrestre propriamente dita, eles desempenham um papel estruturante e essencial na organização da paisagem natural. Estão sempre acompanhados por vegetação ripária especializada como as matas ciliares ou florestas de galeria, que se desenvolvem ao longo de suas margens, adaptadas às condições de alta umidade do solo e às inundações periódicas. Essas matas formam corredores ecológicos contínuos, cruciais para a conectividade entre diferentes ecossistemas, facilitando o deslocamento da fauna, a dispersão de sementes e o fluxo genético entre populações. A vegetação ripária abriga uma biodiversidade única, com espécies vegetais e animais que dependem diretamente desse ambiente de transição entre o terrestre e o aquático."
                    ,"borda":"9,7"},
        "2 time": {"descricao":"Embora os rios não sejam considerados uma fitofisionomia terrestre propriamente dita, eles desempenham um papel estruturante e essencial na organização da paisagem natural. Estão sempre acompanhados por vegetação ripária especializada como as matas ciliares ou florestas de galeria, que se desenvolvem ao longo de suas margens, adaptadas às condições de alta umidade do solo e às inundações periódicas. Essas matas formam corredores ecológicos contínuos, cruciais para a conectividade entre diferentes ecossistemas.",
                    "borda":"8"},
        "3 time": {"descricao":"Embora os rios não sejam considerados uma fitofisionomia terrestre propriamente dita, eles desempenham um papel estruturante e essencial na organização da paisagem natural. Estão sempre acompanhados por vegetação ripária especializada como as matas ciliares ou florestas de galeria, que se desenvolvem ao longo de suas margens, adaptadas às condições de alta umidade do solo e às inundações periódicas.",
                    "borda":"7"},
        "4 time": {"descricao":"Embora os rios não sejam considerados uma fitofisionomia terrestre propriamente dita, eles desempenham um papel estruturante e essencial na organização da paisagem natural. Estão sempre acompanhados por vegetação ripária especializada como as matas ciliares ou florestas de galeria.",
                    "borda":"6,29"}
    }
}


tamanhos = {
    1: {"x1": "22,693", "y1": "4,7244", "tx": "6,5599", "ty": "7,2859"},
    2: {"x1": "22,693", "y1": "4,3987", "tx": "6,7375", "ty": "7,6116"},
    3: {"x1": "22,693", "y1": "4,3987", "tx": "6,5643", "ty": "7,6116"},
    4: {"x1": "22,693", "y1": "4,3987", "tx": "6,6461", "ty": "7,6116"},
}